### PR TITLE
DOCS-564_IMDG_Banner

### PR DESCRIPTION
**Pull request by rebekah-lawrence**
Updated text and link colours. Rebuilt uibundle.

### CODE REVIEW

**Comment by Serdaro** [comment]
@rebekah-lawrence , please make sure to follow https://github.com/hazelcast/hazelcast-docs-ui/blob/master/.github/CONTRIBUTING.adoc#release-task-workflow

**Comment by Serdaro** [comment]
And the changes in question should be included in the relevant source files of this repo, that is, the updated files also need to be pushed.

**Comment by rebekah-lawrence** [comment]
Thanks @Serdaro a few questions before I do it:

- looking at the releases, I have to provide a _.zip_ and a _.tar.gz_ version of the source files?
- this PR can just be closed, to be replaced by the Release?
- In the Release, I leave **Set as the latest release** selected?
- there's no check, I just upload the files to a release and publish?

**Comment by Serdaro** [comment]
> Thanks @Serdaro a few questions before I do it:
> 
> * looking at the releases, I have to provide a _.zip_ and a _.tar.gz_ version of the source files?
> * this PR can just be closed, to be replaced by the Release?
> * In the Release, I leave **Set as the latest release** selected?
> * there's no check, I just upload the files to a release and publish?

* No, zip and tar.gz are created automatically when you make a new release. You just need to attach the ui-bundle.zip to the release. When releasing, it is a convenience to provide the changes in the release description.
* Yes, but there should be a PR in which the relevant files are updated
* Yes
* Yes

**Review by Serdaro — APPROVED** [review]

**Pull request merged**
